chat_messages/urls.py
"""chat URL Configuration"""
from django.urls import path
from .views import (
    MessageView,
    NewMessage,
    DeleteMessage,
    UpdateMessage,
)

urlpatterns = [
    path('', MessageView.as_view(), name='message_view'),
    path('new_message/', NewMessage.as_view(), name='new_message'),
    path('delete_message/<int:pk>', DeleteMessage.as_view(), name='delete_message'),
    path('update_message/<int:message_id>', UpdateMessage.as_view(), name='update_message'),
]

chats/urls.py
"""chat URL Configuration"""
from django.urls import path, include
from .views import (
    ChatsView,
    NewChat,
    DeleteChat,
    HomePageRedirect,
)

app_name = 'chats'

chat_patterns = [
    path('', ChatsView.as_view(), name='chats_list'),
    path('new_chat/', NewChat.as_view(), name='new_chat'),
    path('delete/<int:pk>', DeleteChat.as_view(), name="delete_chat"),
]

urlpatterns = [
    path('', HomePageRedirect.as_view(), name='home'),
    path('chats/<int:user_id>/', include(chat_patterns)),
    path('chats/<int:user_id>/<int:chat_id>/', include('chat_messages.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chats.urls')),
    path('accounts/', include('accounts.urls')),
]

chat_messages/models.py
# Django's libs
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# other app's libs
from chats.models import Chat


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='msg_from')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='msg_to')
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

    def get_absolute_url(self):
        kwargs = {
            "user_id": self.from_user.id,
            "chat_id": self.chat.id,
        }
        return reverse('chat:message_view', kwargs=kwargs)

    def users_list(self):
        users = (
            self.from_user,
            self.to_user,
        )
        return users

chat_messages/forms.py
from django import forms
from .models import Message


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']
        labels = {'text': "Your message"}
        widgets = {
            'text': forms.Textarea(
                attrs={
                    "placeholder": "Message",
                    "class": "form-control rounded-2",
                    "style": "resize: none; height: 50px;",
                })
        }

chat_messages/views.py
# django's libs
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic.edit import BaseUpdateView, BaseCreateView, DeletionMixin, BaseDetailView
from django.contrib.auth.mixins import UserPassesTestMixin
# other app's libs
from chats.views import ChatsView
from chats.models import Chat, ListOfChats
# this app's libs
from .models import Message
from .forms import MessageForm


class MessageView(ChatsView):
    template_name = 'by_bootstrap/message_list.html'
    context_object_name = 'messages_list'
    ordering = ['date']

    def test_func(self):
        inherited_test = ChatsView.test_func(self)
        if not inherited_test:
            return False
        # check the user is chat owner
        chat = get_object_or_404(Chat, id=self.kwargs['chat_id'])
        check_user_chat = self.request.user in chat.users_list()
        return check_user_chat

    def get_queryset(self):
        chat = get_object_or_404(Chat, id=self.kwargs['chat_id'])
        queryset = chat.message_set.all().order_by(*self.ordering)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # get chats content
        context[ChatsView.context_object_name] = ChatsView.get_queryset(self)
        context['chat_id'] = self.kwargs['chat_id']
        # Message form context
        context['message_form'] = MessageForm()
        context['message_form_url'] = reverse(
            viewname='chats:new_message',
            kwargs={
                'user_id': self.kwargs['user_id'],
                'chat_id': self.kwargs['chat_id']
            }
        )
        return context

    def get_success_url(self):
        url = reverse(
            'chats:message_view',
            kwargs={
                'user_id': self.kwargs['user_id'],
                'chat_id': self.kwargs['chat_id'],
            })
        return url


class NewMessage(UserPassesTestMixin, BaseCreateView):
    form_class = MessageForm

    def test_func(self):
        return MessageView.test_func(self)

    def form_valid(self, form):
        # setup
        chat_id = self.kwargs["chat_id"]
        user_id = self.kwargs["user_id"]
        chat_list = ListOfChats.objects.get(user_id=user_id, chat_id=chat_id)
        chat = Chat.objects.get(id=chat_id)
        # set form instances
        form.instance.chat = chat
        form.instance.from_user = chat_list.user
        form.instance.to_user = chat_list.to_user
        return super().form_valid(form)

    def get_success_url(self):
        return MessageView.get_success_url(self)


class UpdateMessage(MessageView, BaseUpdateView):
    form_class = MessageForm
    pk_url_kwarg = 'message_id'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(self, request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Update message form for editing
        context['message_form'] = self.get_form()
        context['message_form_url'] = reverse(
            viewname='chats:update_message',
            kwargs={
                'user_id': self.kwargs['user_id'],
                'chat_id': self.kwargs['chat_id'],
                'message_id': self.kwargs['message_id'],
            }
        )
        return context

    def post(self, request, *args, **kwargs):
        if request.POST.get('find_button'):
            super().post(request, args, kwargs)
            return HttpResponseRedirect(reverse(
                viewname='chats:update_message',
                kwargs={
                    'user_id': self.kwargs['user_id'],
                    'chat_id': self.kwargs['chat_id'],
                    'message_id': self.kwargs['message_id'],
            }))
        return BaseUpdateView.post(self, request, *args, **kwargs)

    def test_func(self):
        inherit_test = super().test_func()
        if not inherit_test:
            return False
        # check user in messages
        message = self.get_object()
        check_user_message = self.request.user == message.from_user
        return check_user_message


class DeleteMessage(UserPassesTestMixin, DeletionMixin, BaseDetailView):
    model = Message

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def test_func(self):
        inherit_test = MessageView.test_func(self)
        if not inherit_test:
            return False
        # check user in message
        message = get_object_or_404(self.model, id=self.kwargs["pk"])
        # message = self.model.objects.get(id=self.kwargs["pk"])
        check_user_message = self.request.user == message.from_user
        return check_user_message

    def get_success_url(self):
        return MessageView.get_success_url(self)

chat_messages/templates/by_bootstrap/message_list.html
{% extends "by_bootstrap/base_chats_list.html" %}

{% block message_section_content %}

    <div style="height: 680px; overflow-y: auto;">

        {# Empty message list #}
        {% if not messages_list %}
            <p>You haven't message.</p>
        {% endif %}

        <!--messages list-->
        {% for message in messages_list %}
            <div class="card text-dark my-2 bg-light {% if message.from_user == user %}border-primary ms-5{% else %}me-5{% endif %}">
                <div class="card-header">
                    <time>{{ message.date|date:"M j, G:i" }}</time>

                    {# edit and delete buttons #}
                    {% if message.from_user == user %}
                        <div class="btn-group float-end">
                            <button class="btn btn-sm bi-three-dots-vertical rounded"
                                    type="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end">
                                <li>
                                    <a class="btn btn-sm btn-outline-info bi-pencil w-100"
                                       href="{% url 'chats:update_message' user_id chat_id message.pk %}"
                                    >edit</a>
                                </li>
                                <li>
                                    <a class="btn btn-sm btn-outline-danger bi-x-lg w-100 mt-1"
                                       href="{% url 'chats:delete_message' user_id chat_id message.pk %}"
                                    >delete</a>
                                </li>
                            </ul>
                        </div>
                    {% endif %}

                </div>
                <div class="card-body">
                    <p class="card-text">{{ message.text|linebreaksbr }}</p>
                </div>
            </div>
        {% endfor %}

    </div>

    <!--new message form-->
    <form class="input-group justify-content-center py-2"
          style="height: 20%;"
          method="post"
          action="{{ message_form_url }}"
    >
        {% csrf_token %}
        {{ message_form.text }}
        <button class="btn btn-outline-primary rounded-circle mx-2 bi bi-send" type="submit"></button>
    </form>

{% endblock message_section_content %}