chat_messages/urls.py
"""chat URL Configuration"""
from django.urls import path
from .views import (
    MessageView,
    NewMessage,
    DeleteMessage,
    UpdateMessage,
)

urlpatterns = [
    path('', MessageView.as_view(), name='message_view'),
    path('new_message/', NewMessage.as_view(), name='new_message'),
    path('delete_message/<int:pk>', DeleteMessage.as_view(), name='delete_message'),
    path('update_message/<int:message_id>', UpdateMessage.as_view(), name='update_message'),
]

chats/urls.py
"""chat URL Configuration"""
from django.urls import path, include
from .views import (
    ChatsView,
    NewChat,
    DeleteChat,
    HomePageRedirect,
)

app_name = 'chats'

chat_patterns = [
    path('', ChatsView.as_view(), name='chats_list'),
    path('new_chat/', NewChat.as_view(), name='new_chat'),
    path('delete/<int:pk>', DeleteChat.as_view(), name="delete_chat"),
]

urlpatterns = [
    path('', HomePageRedirect.as_view(), name='home'),
    path('chats/<int:user_id>/', include(chat_patterns)),
    path('chats/<int:user_id>/<int:chat_id>/', include('chat_messages.urls')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chats.urls')),
    path('accounts/', include('accounts.urls')),
]

chats/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


class Chat(models.Model):
    id = models.BigAutoField(primary_key=True)

    def delete(self, using=None, keep_parents=False):
        """Delete this chat and all entries in ListOfChats"""
        super().delete(using, keep_parents)
        self._delete_from_users_list()

    def _delete_from_users_list(self):
        """Delete all entries in ListOfChats"""
        chats_list = self.listofchats_set.filter(chat_id=self.id)
        for chat in chats_list:
            chat.delete()

    def users_list(self):
        users = []
        for chat_in_list in self.listofchats_set.all():
            users.append(chat_in_list.user)
        return users

    def __str__(self):
        return f"chat_id={self.id}"


class ListOfChats(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET(get_user_model()),
        related_name='chatslist',
    )
    to_user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='chat_to_user',
    )
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.to_user.username

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        """Check chat in users exist chats. Create chat and entries in ListOfChats if chat doesn't exist"""
        # check chat in user's exist chats
        check_in_user_list = ListOfChats.objects.filter(user=self.user, to_user=self.to_user)
        check_in_to_user_list = ListOfChats.objects.filter(user=self.to_user, to_user=self.user)

        if check_in_user_list.count():
            pass
        elif (not check_in_user_list.count()) and (not check_in_to_user_list.count()):
            self.chat = self._create_chat()
            super().save(force_insert, force_update, using, update_fields)
            self._add_in_to_user_list()
        elif check_in_to_user_list.count():
            chat_in_list = check_in_to_user_list.get()
            self.chat = chat_in_list.chat
            super().save(force_insert, force_update, using, update_fields)

    def delete(self, using=None, keep_parents=False):
        """Delete the Chat if it is the last entry in ListOfChat"""
        entries_num = self.chat.listofchats_set.all().count()
        if entries_num == 1:
            self.chat.delete()
        else:
            super().delete(using, keep_parents)

    def _create_chat(self):
        """Create chat"""
        chat = Chat.objects.create()
        chat.save()
        return chat

    def _add_in_to_user_list(self):
        """Create a entry in to_user's ListOfChats"""
        chat_list = ListOfChats.objects.create(
            user=self.to_user,
            to_user=self.user,
        )
        chat_list.save()

chats/forms.py
from django import forms
from .models import ListOfChats


class AddChatForm(forms.ModelForm):
    class Meta:
        model = ListOfChats
        fields = {'to_user': 'user2'}
        widgets = {
            'to_user': forms.HiddenInput(),
        }

chats/views.py
# django's libs
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import ListView, RedirectView
from django.views.generic.edit import BaseCreateView, BaseDeleteView
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
# other app's libs
from find_users.views import FindFormView
# this app's libs
from .models import ListOfChats
from .forms import AddChatForm


class HomePageRedirect(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        user_id = self.request.user.id
        url = reverse('chats:chats_list', kwargs={'user_id': user_id})
        return url


class ChatsView(UserPassesTestMixin, ListView):
    model = ListOfChats
    template_name = 'by_bootstrap/base_chats_list.html'
    context_object_name = 'chats_list'
    find_form = FindFormView()

    def test_func(self):
        return self.request.user.id == self.kwargs["user_id"]

    def get_queryset(self):
        user_id = self.request.user.id
        queryset = self.model.objects.filter(user=user_id)
        queryset = self.find_form.get_filtered_queryset(queryset)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_id'] = self.kwargs['user_id']
        context['chat_id'] = None
        # set find form context
        context.update(self.find_form.get_context_data())
        return context

    def get(self, request, *args, **kwargs):
        self.find_form.get(request, args, kwargs)
        return super().get(request, args, kwargs)

    def post(self, request, *args, **kwargs):
        self.find_form.post(request, *args, **kwargs)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('chats:chats_list', kwargs={'user_id': self.kwargs['user_id']})


class NewChat(UserPassesTestMixin, BaseCreateView):
    form_class = AddChatForm

    def test_func(self):
        return ChatsView.test_func(self)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.to_user.id = self.request.POST['to_user']
        return super().form_valid(form)

    def form_invalid(self, form):
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        """redirect to the new chat messages"""
        url = reverse(
            'chats:message_view',
            kwargs={
                'user_id': self.kwargs['user_id'],
                'chat_id': self.object.chat.id
            })
        return url


class DeleteChat(UserPassesTestMixin, BaseDeleteView):
    model = ListOfChats

    def test_func(self):
        inherited_test = ChatsView.test_func(self)
        # check the user is chat owner
        chat_in_list = self.get_object()
        check_user_chat = self.request.user == chat_in_list.user
        return inherited_test and check_user_chat

    def get_success_url(self):
        return ChatsView.get_success_url(self)

chats/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}MyChat{% endblock title %}</title>
    <link href="{% static "chats/base_style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "chats/user_info_style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "chats/chat_list_style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "chat_messages/messages_list_style.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "chat_messages/message_style.css" %}" rel="stylesheet" type="text/css">
</head>

<body>

<main id="main_section">

    <section id="contacts_section">

        {% block contacts_section_content %}
            <p>
                You haven't any chats:(<br>
                Use upper form to find users.
            </p>
        {% endblock contacts_section_content %}
    </section>

    <section id="message_section">
        {% block message_section_content %}
            <h2>Choice your chat</h2>
        {% endblock message_section_content %}
    </section>

</main>

</body>

</html>

chats/templates/base_chats_list.html
{% extends 'base.html' %}
{% load static %}

{% block contacts_section_content %}

    <section id="user_info_section">

        <div class="user_info_card">
            <img class="user_avatar"
                 src="{% static "chats/img/default/no_avatar.png" %}"
                 alt="{{ user.username }}"
            />
            <p class="users_contacts">{{ user.username }}</p>

            <div class="dropdown">
                <button class="dropbtn">act.</button>
                <div class="dropdown-content">
                    <a href="#">Home page</a>
                    <a href="#">Change password</a>
                    <hr>
                    <a href="{% url 'accounts:logout' %}">LogOut</a>
                </div>
            </div>

        </div>

    </section>

    <form id="find_form" method="post">
        {% csrf_token %}
        {{ find_form.find_field }}
        <button type="submit" name="find_button" value="find">Find</button>
    </form>

    <section id="chats_list">

        {% if find_flag and chats_list %}
            <p>Your chats:</p><hr>{% endif %}

        {% if not find_flag and not chats_list %}
            <p>
                You haven't chats.<br>
                Use upper form to find and add new chat.
            </p>
        {% endif %}

        {# __________own user's chats list_____________ #}
        {% for chat in chats_list %}
            {# User chat card #}
            <a class="chat_view {% if chat.chat.id == chat_id %}active_chat{% endif %}"
               href="{% url 'chats:message_view' user_id chat.chat.id %}"
            >
                <img class="user_avatar"
                     src="{% static "chats/img/default/no_avatar.png" %}"
                     alt="{{ user.user.username }}_avatar"
                />
                <p>{{ chat }}</p>
                <form class="delete_chat"
                      method="post"
                      action="{% url 'chats:delete_chat' user_id chat.id %}"
                >
                    {% csrf_token %}
                    <button type="submit">X</button>
                </form>
            </a>

        {% endfor %}

        {# _______New users list_________ #}
        {% if find_flag %}

            {% if not users_list %}
                <p>Can't find any new user.</p>
            {% endif %}

            {% if users_list %}
                <p>Add new chat:</p><hr>
            {% endif %}

            {% for user in users_list %}
                {# New user chat card #}
                <a class="chat_view" href="#">
                    <img class="user_avatar"
                         src="{% static "chats/img/default/no_avatar.png" %}"
                         alt="{{ user.username }}_avatar"
                    />
                    <p>{{ user.username }}</p>
                    <form class="add_chat" method="post" action="{% url 'chats:new_chat' user_id %}">
                        {% csrf_token %}
                        <input type="hidden" name="to_user" value="{{ user.id }}">
                        <button type="submit">Add</button>
                    </form>
                </a>

            {% endfor %}
        {% endif %}

    </section>

{% endblock contacts_section_content %}